env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    my_og_token: "ENCRYPTED[!d96db82b7b5ac8a92b77d2cbbbc52e845c5a8797af0e047e360ae1e774347d2cb5a87440e53af61855bd1e75e1f4d620!]" # main id
    github_token: "ENCRYPTED[!b37d560adaeb2a229b43a007b506361590ebf8ee0c8dd3ed643dd265921a16a1e9c6cd30813ab8888843e3630f4e06b0!]" # alt id
    bot_api: "ENCRYPTED[!c262f1e147caa787ff1ff0923ce95604e26b01fdedf819bd14e5d9d2a9028d7dd8af95f4f364d841ea4819891d46c76a!]"
    chat_id: "-1001675070042"
    v_core: "16"
    s_core: "16"
    git_cookies: 0
    REAL_REPO_OWNER: "ashraysingh" # main id

# store information about git here
    gmail: ehteshammalik18998@gmail.com

task:
    name: rdcmf
    timeout_in: 120m
    container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
    down_background_script:
      - git clone -b main https://$REAL_REPO_OWNER:$my_og_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
