#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 -g default,-mips,-darwin,-notdefault
#git clone https://github.com/wHo-EM-i/manifest.git --depth 1 -b 13-4.19 .repo/local_manifests

# Sync source without unnecessary messages, try with -j16 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# tree
git clone --depth=1 https://github.com/ashraysingh/android_device_xiaomi_haydn device/xiaomi/haydn -b lineage-20
git clone --depth=1 https://github.com/ashraysingh/proprietary_vendor_xiaomi_haydn vendor/xiaomi/haydn -b lineage-20
git clone --depth=1 https://github.com/ashraysingh/android_device_xiaomi_sm8350-common device/xiaomi/sm8350-common -b lineage-20
git clone --depth=1 https://github.com/ashraysingh/proprietary_vendor_xiaomi_sm8350-common vendor/xiaomi/sm8350-common -b lineage-20

# Kernel
echo 'Cloning kernel tree'
git clone --depth=1 https://github.com/ashraysingh/android_kernel_xiaomi_sm8350 -b lineage-20 kernel/xiaomi/sm8350
cd kernel/xiaomi/sm8350
git submodule init && git submodule update KernelSU
cd ../../..

# Xiaomi
echo 'Cloning hardware xiaomi'
git clone --depth=1 https://github.com/ashraysingh/android_hardware_xiaomi hardware/xiaomi -b 13.0

# Firmware
echo 'Cloning firmware'
git clone https://gitlab.com/Alucard_Storm/vendor_xiaomi_haydn-firmware -b thirteen vendor/xiaomi/haydn-firmware

# Camera
echo 'Cloning Leica Camera'
git clone --depth=1 https://gitlab.com/Alucard_Storm/haydn-miuicamera -b thirteen-leica vendor/xiaomi/haydn-miuicamera

# Camera Patch
cd /tmp/rom/frameworks/base
curl https://github.com/ashraysingh/android_frameworks_base-1/commit/45ff9297073b13b27d67f86771a48d744b4530ab.patch | git am
curl https://github.com/ashraysingh/android_frameworks_base-1/commit/f13400c38286937d86724a05b7a2476e86ab04cf.patch | git am

#git clone --depth=1 https://github.com/arrowos-devices/android_hardware_xiaomi hardware/xiaomi -b arrow-13.1

#rm -rf /tmp/rom/device/xiaomi/lavender/libhidl
#rm -rf /tmp/rom/hardware/xiaomi/megvii/*.bp

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
