#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/SuperiorOS/manifest.git -b thirteen -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j16 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# tree
git clone --depth=1 https://github.com/ashraysingh/android_device_xiaomi_haydn device/xiaomi/haydn -b superior
git clone --depth=1 https://github.com/ashraysingh/proprietary_vendor_xiaomi_haydn vendor/xiaomi/haydn -b lineage-20
git clone --depth=1 https://github.com/ashraysingh/android_device_xiaomi_sm8350-common device/xiaomi/sm8350-common -b superior
git clone --depth=1 https://github.com/ashraysingh/proprietary_vendor_xiaomi_sm8350-common vendor/xiaomi/sm8350-common -b lineage-20

# Kernel
echo 'Cloning kernel tree'
git clone --depth=1 --recursive https://github.com/ashraysingh/android_kernel_xiaomi_sm8350 -b lineage-20 kernel/xiaomi/sm8350
cd kernel/xiaomi/sm8350
git submodule init && git submodule update KernelSU
cd ../../..

# Xiaomi
echo 'Cloning hardware xiaomi'
rm -rf hardware/xiaomi && git clone --depth=1 https://github.com/LineageOS/android_hardware_xiaomi -b lineage-20 hardware/xiaomi

# Firmware
echo 'Cloning firmware'
git clone https://gitlab.com/Alucard_Storm/vendor_xiaomi_haydn-firmware -b thirteen vendor/xiaomi/haydn-firmware

# Camera
echo 'Cloning Leica Camera'
git clone --depth=1 https://gitlab.com/Alucard_Storm/haydn-miuicamera -b thirteen-leica vendor/xiaomi/haydn-miuicamera

echo 'Adding slow-mo fix for Leica Camera'
cd hardware/interfaces
wget https://raw.githubusercontent.com/Astridxx/Patch-haydn/Octavi-13/0003-Update-HIDL-overrideFormat-from-HAL.patch
patch -p1 <0003-Update-HIDL-overrideFormat-from-HAL.patch
cd ../..

echo 'Expose aux camera if packagename is null'
cd frameworks/base
wget https://raw.githubusercontent.com/Astridxx/Patch-haydn/Rising-13/0001-Expose-aux-camera-if-packagename-is-null.patch
wget https://raw.githubusercontent.com/Astridxx/Patch-haydn/Rising-13/0002-Dont-crash-when-checking-input-configuration-failed.patch
wget https://raw.githubusercontent.com/Astridxx/Patch-haydn/Rising-13/0003-Add-backwards-compatible-CaptureResultExtras-constructor.patch
patch -p1 <0001-Expose-aux-camera-if-packagename-is-null.patch
patch -p1 <0002-Dont-crash-when-checking-input-configuration-failed.patch
patch -p1 <0003-Add-backwards-compatible-CaptureResultExtras-constructor.patch
cd ../..
#git clone --depth=1 https://github.com/arrowos-devices/android_hardware_xiaomi hardware/xiaomi -b arrow-13.1

#rm -rf /tmp/rom/device/xiaomi/lavender/libhidl
#rm -rf /tmp/rom/hardware/xiaomi/megvii/*.bp

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
